import Head from 'next/head'
import Link from 'next/link'
import { useAuth } from '@/hooks'

export default function Home() {
  const {user, logOut} = useAuth();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        { user ? ( 
          <div> 
            Hola
            <button onClick={logOut}>Cerrar sesión</button>
          </div> 
        ) : ( 
          <div>
            <Link href='/auth/sign-in'>
              Iniciar sesión
            </Link>
          </div>
        ) }
      </main>
    </>
  )
}
