import Head from 'next/head'
import classNames from 'classnames';

import { TopBar } from '@/components';

interface MainLayoutProps {
    isOpenSearch?: boolean;
    isContainer?: boolean;
    relative?: boolean;
    children: React.ReactNode;
}

export const MainLayout = ({ children, isOpenSearch = false, isContainer = false, relative = false }: MainLayoutProps) => {
    return (
        <>
            <Head>
                <title>Modulag</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <TopBar/>
                <div className={classNames({ ['pt-16']: relative }) + ' mx-auto max-w-7xl px-4 sm:px-6 lg:px-8'}>
                    { isContainer ? 
                        <div className="mx-auto max-w-3xl">
                            {children}
                        </div>
                    : <> { children } </> }
                 </div>
            </main>
        </>
    )
}